### PR TITLE
Add controls export from hub.armosec.io.

### PR DESCRIPTION
**Pull request by craigbox**
Signed-off-by: Craig Box <craigb@armosec.io>

### CODE REVIEW

**Comment by dwertent** [comment]
@slashben @yuleib do we have a way of automating this?

**Comment by yuleib** [comment]
@dwertent - not sure regarding what you are referring to

**Comment by dwertent** [comment]
@yuleib 
Craig copied the controls from [armosec docs](https://hub.armosec.io/docs).
This is manually copied and will not be updated every time we release a version in the regolibrary.
So we cant rely on this docs because they will be out off date the moment we change.

**Comment by slashben** [comment]
@dwertent sure there is

**Comment by yuleib** [comment]
this is not true. we have the following [script](https://github.com/kubescape/regolibrary/blob/master/scripts/upload-readme.py) which also part of the regolibrary release. 
we had an issue with the script previously but i fixed it last week. 
should be workign fine now

**Comment by craigbox** [comment]
Can you believe it, [I have an LFX Mentorship student working on exactly this](https://github.com/kubescape/kubescape/issues/1302)!

@TRohit20 is finishing up a pipeline to automatically create PRs in this repo when a release is made in `regolibrary`.  This PR was part of the demo for that work and can be ignored for now.

**Comment by TRohit20** [comment]
Hey @dwertent already working on the same. Adding a script to run on release to generate docs for controls. Post which the docs folder will be auto-synced with the website repo. Here's a sample PR auto-generated: https://github.com/TRohit20/kubescape.io/pull/1 (Sample PR, yet to finish the pipeline, will refine for thorough implementation to the `main` branch) . Once I finish setting up the pipeline, the PR raised will be auto merged.

**Review by dwertent — APPROVED** [review]

**Comment by dwertent** [comment]
@craigbox Can you please rebase?

**Comment by craigbox** [comment]
We won't merge this; we'll merge #31 and generate new docs, which should be the same output.

**Pull request closed without merging**
